=== Manish4586/android_platform_qcom_common/data/mobileap/src/mobileap_cfg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2011 sp1 (x64) (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="system">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="MobileAPCfg"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Enable">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Module">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="ar6000"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="WlanGpioNum">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="21"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DevMode">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="AP"/>
				<xs:enumeration value="STA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="AccessProfile">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="FULL"/>
				<xs:enumeration value="INTERNETONLY"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DHCPCfg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="StartIP"/>
				<xs:element ref="EndIP"/>
				<xs:element ref="LeaseTime"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="EnableSupplicant">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="STAModeConnType">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="SupplicantCfg">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="/etc/wpa_supplicant.conf"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ExternalAPSSID">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="dlink-ap"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="StartIP">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="192.168.1.20"/>
				<xs:enumeration value="192.168.2.20"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LeaseTime">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="12h"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="EndIP">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="192.168.1.40"/>
				<xs:enumeration value="192.168.2.40"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="SSID2Cfg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Enable"/>
				<xs:element ref="DevMode"/>
				<xs:element ref="HostAPDCfg"/>
				<xs:element ref="APIPAddr"/>
				<xs:element ref="SubNetMask"/>
				<xs:element ref="AccessProfile"/>
				<xs:element ref="EnableDHCPServer"/>
				<xs:element ref="DHCPCfg"/>
				<xs:element ref="EnableSupplicant"/>
				<xs:element ref="SupplicantCfg"/>
				<xs:element ref="ExternalAPSSID"/>
				<xs:element ref="STAModeConnType"/>
				<xs:element ref="StaticIPAddr"/>
				<xs:element ref="StaticConfigDNSAddr"/>
				<xs:element ref="StaticConfigGWAddr"/>
				<xs:element ref="StaticConfigNetMask"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="SSID3Cfg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Enable"/>
				<xs:element ref="DevMode"/>
				<xs:element ref="HostAPDCfg"/>
				<xs:element ref="APIPAddr"/>
				<xs:element ref="SubNetMask"/>
				<xs:element ref="AccessProfile"/>
				<xs:element ref="EnableDHCPServer"/>
				<xs:element ref="DHCPCfg"/>
				<xs:element ref="EnableSupplicant"/>
				<xs:element ref="SupplicantCfg"/>
				<xs:element ref="ExternalAPSSID"/>
				<xs:element ref="STAModeConnType"/>
				<xs:element ref="StaticIPAddr"/>
				<xs:element ref="StaticConfigDNSAddr"/>
				<xs:element ref="StaticConfigGWAddr"/>
				<xs:element ref="StaticConfigNetMask"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="V4_UMTS_PROFILE_INDEX">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="V6_UMTS_PROFILE_INDEX">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="TECH">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="ANY"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="SubNetMask">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="255.255.255.0"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="MobileAPWanCfg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="AutoConnect"/>
				<xs:element ref="Roaming"/>
				<xs:element ref="EriConfig"/>
				<xs:element ref="TECH"/>
				<xs:element ref="V4_UMTS_PROFILE_INDEX"/>
				<xs:element ref="V4_CDMA_PROFILE_INDEX"/>
				<xs:element ref="V6_UMTS_PROFILE_INDEX"/>
				<xs:element ref="V6_CDMA_PROFILE_INDEX"/>
				<xs:element ref="IPFamily"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MobileAPNatCfg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="IoEMode"/>
				<xs:element ref="TetheringOnly"/>
				<xs:element ref="NATType"/>
				<xs:element ref="FirewallEnabled"/>
				<xs:element ref="FirewallPktsAllowed"/>
				<xs:element ref="Firewall"/>
				<xs:element ref="PortFwding"/>
				<xs:element ref="NatEntryTimeout"/>
				<xs:element ref="DmzIP"/>
				<xs:element ref="EnableIPSECVpnPassthrough"/>
				<xs:element ref="EnablePPTPVpnPassthrough"/>
				<xs:element ref="EnableL2TPVpnPassthrough"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MobileAPLanCfg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Module"/>
				<xs:element ref="DevMode"/>
				<xs:element ref="HostAPDCfg"/>
				<xs:element ref="APIPAddr"/>
				<xs:element ref="SubNetMask"/>
				<xs:element ref="AccessProfile"/>
				<xs:element ref="EnableDHCPServer"/>
				<xs:element ref="DHCPCfg"/>
				<xs:element ref="SSID2Cfg"/>
				<xs:element ref="SSID3Cfg"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="MobileAPCfg">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="MobileAPNatCfg"/>
				<xs:element ref="MobileAPLanCfg"/>
				<xs:element ref="MobileAPWanCfg"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Roaming">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="EriConfig">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="/etc/mobileap_eri_config.bin"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PortFwdingProtocol">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="17"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PortFwdingPrivatePort">
		<xs:simpleType>
			<xs:restriction base="xs:short">
				<xs:enumeration value="5500"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PortFwdingPrivateIP">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="192.168.1.8"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PortFwdingGlobalPort">
		<xs:simpleType>
			<xs:restriction base="xs:short">
				<xs:enumeration value="5500"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PortFwding">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="PortFwdingPrivateIP"/>
				<xs:element ref="PortFwdingPrivatePort"/>
				<xs:element ref="PortFwdingGlobalPort"/>
				<xs:element ref="PortFwdingProtocol"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="NatEntryTimeout">
		<xs:simpleType>
			<xs:restriction base="xs:short">
				<xs:enumeration value="200"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="IPFamily">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="IPv4"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="HostAPDCfg">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="/etc/hostapd.conf"/>
				<xs:enumeration value="/etc/hostapd-eth1.conf"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType> 
	</xs:element>
	<xs:element name="FirewallProtocol">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="6"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FirewallEndPort">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="23"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FirewallStartPort">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="23"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="IoEMode">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="TetheringOnly">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NATType">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="SYM"/>
				<xs:enumeration value="PRC"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FirewallEnabled">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FirewallPktsAllowed">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Firewall">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FirewallStartPort"/>
				<xs:element ref="FirewallEndPort"/>
				<xs:element ref="FirewallProtocol"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="EnablePPTPVpnPassthrough">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="EnableL2TPVpnPassthrough">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="EnableIPSECVpnPassthrough">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="EnableHostAPD">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="EnableDHCPServer">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
				<xs:enumeration value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DmzIP">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="0.0.0.0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="V4_CDMA_PROFILE_INDEX">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="V6_CDMA_PROFILE_INDEX">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="AutoConnect">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="APIPAddr">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="192.168.1.1"/>
				<xs:enumeration value="192.168.2.1"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="StaticIPAddr">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="0.0.0.0"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="StaticConfigDNSAddr">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="0.0.0.0"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="StaticConfigGWAddr">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="0.0.0.0"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="StaticConfigNetMask">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="0.0.0.0"/>
				<xs:enumeration value="NA"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== Manish4586/android_platform_qcom_common/data/mobileap/src/mobileap_cfg.xml
<?xml version="1.0" encoding="UTF-8"?>
<system xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mobileap_cfg.xsd">
	<MobileAPCfg>
		<MobileAPNatCfg>
			<IoEMode>1</IoEMode>
			<TetheringOnly>0</TetheringOnly>
			<NATType>SYM</NATType>
			<FirewallEnabled>1</FirewallEnabled>
			<FirewallPktsAllowed>0</FirewallPktsAllowed>
			<Firewall>/etc/mobileap_firewall.xml</Firewall>
			<PortFwding>
				<PortFwdingPrivateIP>192.168.225.8</PortFwdingPrivateIP>
				<PortFwdingPrivatePort>1500</PortFwdingPrivatePort>
				<PortFwdingGlobalPort>1500</PortFwdingGlobalPort>
				<PortFwdingProtocol>17</PortFwdingProtocol>
			</PortFwding>
			<NatEntryTimeout>200</NatEntryTimeout>
			<DmzIP>0.0.0.0</DmzIP>
			<EnableIPSECVpnPassthrough>1</EnableIPSECVpnPassthrough>
			<EnablePPTPVpnPassthrough>1</EnablePPTPVpnPassthrough>
			<EnableL2TPVpnPassthrough>1</EnableL2TPVpnPassthrough>
		</MobileAPNatCfg>
		<MobileAPLanCfg>
			<Module>ar6000</Module>
			<DevMode>AP</DevMode>
			<HostAPDCfg>/etc/hostapd.conf</HostAPDCfg>
			<APIPAddr>192.168.225.1</APIPAddr>
			<SubNetMask>255.255.255.0</SubNetMask>
			<AccessProfile>FULL</AccessProfile> 
			<EnableDHCPServer>1</EnableDHCPServer>
			<DHCPCfg>
				<StartIP>192.168.225.20</StartIP>
				<EndIP>192.168.225.40</EndIP>
				<LeaseTime>12h</LeaseTime>
			</DHCPCfg> 
			<SSID2Cfg>
				<Enable>0</Enable>
				<DevMode>AP</DevMode>
				<HostAPDCfg>/etc/hostapd-eth1.conf</HostAPDCfg>
				<APIPAddr>192.168.2.1</APIPAddr>
				<SubNetMask>255.255.255.0</SubNetMask>
				<AccessProfile>INTERNETONLY</AccessProfile>
				<EnableDHCPServer>1</EnableDHCPServer>
				<DHCPCfg>
					<StartIP>192.168.2.20</StartIP>
					<EndIP>192.168.2.40</EndIP>
					<LeaseTime>12h</LeaseTime>
				</DHCPCfg> 
				<EnableSupplicant>0</EnableSupplicant>
				<SupplicantCfg>NA</SupplicantCfg>
				<ExternalAPSSID>NA</ExternalAPSSID>
				<STAModeConnType>NA</STAModeConnType>
				<StaticIPAddr>NA</StaticIPAddr>
				<StaticConfigDNSAddr>NA</StaticConfigDNSAddr>
				<StaticConfigGWAddr>NA</StaticConfigGWAddr>
				<StaticConfigNetMask>NA</StaticConfigNetMask>
			</SSID2Cfg> 
			<SSID3Cfg>
				<Enable>0</Enable>
				<DevMode>STA</DevMode>
				<HostAPDCfg>NA</HostAPDCfg>
				<APIPAddr>NA</APIPAddr>
				<SubNetMask>NA</SubNetMask>
				<AccessProfile>NA</AccessProfile>
				<EnableDHCPServer>0</EnableDHCPServer>
				<DHCPCfg>
					<StartIP>NA</StartIP>
					<EndIP>NA</EndIP>
					<LeaseTime>NA</LeaseTime>
				</DHCPCfg> 
				<EnableSupplicant>1</EnableSupplicant>
				<SupplicantCfg>/etc/wpa_supplicant.conf</SupplicantCfg>
				<ExternalAPSSID>dlink-ap</ExternalAPSSID>
				<STAModeConnType>0</STAModeConnType>
				<StaticIPAddr>0</StaticIPAddr>
				<StaticConfigDNSAddr>0</StaticConfigDNSAddr>
				<StaticConfigGWAddr>0</StaticConfigGWAddr>
				<StaticConfigNetMask>0</StaticConfigNetMask>
			</SSID3Cfg>
		</MobileAPLanCfg>
		<MobileAPWanCfg>
			<AutoConnect>0</AutoConnect>
			<Roaming>0</Roaming>
			<EriConfig>/etc/mobileap_eri_config.bin</EriConfig>
			<TECH>ANY</TECH>
			<V4_UMTS_PROFILE_INDEX>1</V4_UMTS_PROFILE_INDEX>
			<V4_CDMA_PROFILE_INDEX>0</V4_CDMA_PROFILE_INDEX>
			<V6_UMTS_PROFILE_INDEX>0</V6_UMTS_PROFILE_INDEX>
			<V6_CDMA_PROFILE_INDEX>0</V6_CDMA_PROFILE_INDEX>
			<IPFamily>IPv4</IPFamily>
		</MobileAPWanCfg>
	</MobileAPCfg>
</system>
